services:
  - docker

dist: trusty
language: python

install:
  - docker run -e PYABI=$PYABI -v $(pwd):/pytomlpp -w /pytomlpp quay.io/pypa/manylinux2010_x86_64 ci/build-wheel.sh wheels/
  - ls wheels/
  - pip install -U pip setuptools wheel
  - pip install wheels/*.whl
  - pip install -r tests/requirements.txt

script: pytest -vvra

jobs:
  include:
    # - python: 2.7
    #   env: PYABI=cp27-cp27mu
    #   before_script: pip install pathlib2
    - python: 3.5
      env: PYABI=cp35-cp35m
    - python: 3.6
      env: PYABI=cp36-cp36m
    - dist: xenial
      python: 3.7
      env: PYABI=cp37-cp37m
    - dist: xenial
      python: 3.8
      env: PYABI=cp38-cp38
    - dist: xenial
      python: 3.9-dev
      env: PYABI=cp39-cp39

    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - cmake
      install:
        - export CC=gcc-8
        - export CXX=g++-8
        - cmake -B build/test -S tests
        - cmake --build build/test -j4
      script:
        - ./build/test/pytomlpp-test