package:
  name: pytomlpp
  version: {{ '0.1.0' }}

build:
  number: 0

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - cmake
    - pybind11=2.5
  run:
    - python

test:
  imports:
    - pytomlpp

about:
  home: https://github.com/bobfang1992/pytomlpp
  summary: Python wrapper for tomlplusplus
  license: MIT
