# Build, test and publish wheels to PyPI
# Build and test run on every push
# Publish runs only on a tag push
# Note: This does not publish sdist
name: Wheels (Linux)

on: [push, pull_request]

jobs:
  build:
    name: Build wheels on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: 3.8

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.4.2

    - name: Build wheels
      env:
        # Skip building on Python 2.7
        CIBW_SKIP: cp27-* pp27-*
        CIBW_BEFORE_TEST: pip install -r tests/requirements.txt
        CIBW_TEST_COMMAND: pytest {project}/tests
      run: |
        python -m cibuildwheel --output-dir dist

    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
