# Build, test and publish wheels to PyPI
# Build and test run on every push
# Publish runs only on a tag push
# Note: This does not publish sdist
name: Wheels (Windows)

on: [push, pull_request]

jobs:
  build:
    name: Build wheels on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: 3.8

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.4.2

    - name: Build wheels
      env:
        # Skip building on Python 2.7
        # Additionally, skip 32-bit Windows for now as MSVC needs seperate setup with different toolchain to do this
        # Refer: https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/#windows-and-python-27
        CIBW_SKIP: cp27-* pp27-* *-win32
        CIBW_TEST_REQUIRES: pytest
        CIBW_TEST_COMMAND: pytest {project}/tests
      run: |
        python -m cibuildwheel --output-dir dist

    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
